Kirchhoff-/Android-Interview-Questions

- Android/What are Intents.md
> What are Intents

- Android/What are Pending Intent.md
> What are Pending Intent

- Java/Can a static method be overridden.md
> Can a static method be overriden

- Java/Different between Array and ArrayList.md
> Different between Array and ArrayList

- Android/How does RecyclerView differ from ListView.md
> How does RecyclerView differ from ListView

- Android/What are the permission protection levels.md
> Answer for permission protection levels

- Android/What is the difference between Serializable and Parcelable.md
> Difference between Serializable and Parcelable

- Java/What is the difference between overriding and overloading.md
> Difference between overriding and overloading

- Android/Different between @id and @+id.md
> Different between @id and @+id

- Java/Final modifier.md
> Answer for final modifier

- Kotlin/What's difference between == and ===.md
> Wha's difference between == and ===

- Android/What is the difference between Dialog & DialogFragment.md
> Difference beween dialog and dialogFragment

- Android/What is SurfaceView.md
> Answer for What is SurfaceView

- Android/What is AndroidManifest.md
> What is AndroidManifest

- Java/Method signature.md
> Answer for Java method signature

- Kotlin/What's init block.md
> Answer for What is init block

- Java/What does the keyword synchronized mean.md
> Synchronized keyword

- Kotlin/What's Companion Objects.md
> Answer for What's Companion Objects

- Android/What is Overdraw.md
> What is Overdraw

- Android/What are Sticky Intent.md
> Answer for What are Sticky Intent

- Java/Difference between int and Integer.md
> Difference between int and Integer

- Rx/Observable types.md
> Answer for observable types

- Kotlin/What's inline class.md
> Kotlin inline class

- Java/Can a constructor be inherited.md
> Java constructor inherited

- Rx/RepeatWhen vs RetryWhen.md
> Difference between RepeatWhen and RetryWhen

- Kotlin/What's a const.md
> What's a const

- Java/References types.md
> Java references types

- Kotlin/What's lateinit.md
> Lateinit modifier

- Android/Launch modes.md
> Launch modes

- Java/What are anonymous classes.md
> Anonymous classes

- Android/What is Proguard.md
> What's proguard

- Rx/What's backpressure.md
> What's backpressure

- Android/Difference between raw and assets folders.md
> Difference between raw and assets folders

- Java/Difference between Abstract class and Interfaces.md
> Abstract class vs interface

- Android/What's ViewStub.md
> What's ViewStub

- Java/try-catch-finally.md
> Try-catch-finally

- Kotlin/Inline keyword.md
> Kotlin inline keyword

- Java/What's Comparable and Comparator interface.md
> Comparable vs comparator

- Java/What are the methods of Object class.md
> Object class methods

- General/Describe Scrum and Kanban.md
- README.md
> Scrum vs Kanban

- General/What is the difference between TCP and UDP.md
> What is the difference between TCP and UDP

- Kotlin/What's the difference between lazy and lateinit.md
> Lazy vs Lateinit

- Java/What are lambda expressions.md
- README.md
> Lambda expressions

- Kotlin/What's data classes.md
> What's data classes

- Java/What's Clonaeble interface.md
- README.md
> Clonaeble interface

- General/What is the difference between HTTP and HTTPS.md
> Difference between HTTP and HTTPS

- General/What is the difference between GET and POST request.md
- README.md
> Difference between GET and POST

- General/What is the difference between PUT and POST request.md
- README.md
> PUT vs POST

- Java/What is the difference between String, StringBuilder and StringBuffer.md
> String vs StringBuffer vs StringBuilder

- Java/What is transient keyword.md
- README.md
> transient keyword

- README.md
- Rx/Schedulers types.md
> Schedulers types

- Kotlin/sealed classes.md
- README.md
> Sealed classes

- Java/What is functional interface.md
- README.md
> Functional interface

- Java/ArrayList vs LinkedList.md
- README.md
> ArrayList vs LinkedList

- Android/What is installLocation tag in AndroidManifest.md
- README.md
> installLocation tag in AndroidManifest

- Kotlin/What's Sequence.md
- README.md
> Kotlin sequence

- Java/What is immutable object.md
- README.md
> Immutable object

- Java/What is enum.md
- README.md
> What's enum

- Java/What is the difference between a Stream and an Iterator.md
- README.md
> Stream vs iterator

- Java/Difference between static and regular nested classes.md
- README.md
> Static vs Nested classes in Java

- Android/Service vs IntentService.md
- README.md
> Service vs IntentService

- Java/What is object monitor.md
- README.md
> Object monitor

- Kotlin/What are coroutines.md
- README.md
> Kotlin coroutines

- README.md
- Testing/What is JUnit.md
> What is JUnit

- Kotlin/Object keyword.md
- README.md
> Object keyword Kotlin

- Kotlin/Difference between Nested Class and Inner Class.md
- README.md
> nested vs inner classes

- Kotlin/Reified keyword.md
- README.md
> reified keyword

- Kotlin/val mutableList vs var immutableList. When to use which.md
- README.md
> val mutableList vs var immutableList

- README.md
- Testing/Difference between JUnit 4 and JUnit 5.md
> junit4 vs junit5

- Java/How HashMap works.md
- README.md
> How HashMap works in Java

- Patterns/Types of Design Patterns.md
- README.md
> Types of Design Patterns

- README.md
- Testing/What you know about Mockito library.md
> Mockito library

- README.md
- Testing/What you know about espresso.md
> espresso library

- Kotlin/map vs flatMap in collections.md
- README.md
> Map() vs FlatMap() kotlin

- README.md
- Testing/Difference between mock, fake and stub.md
> Mock, stub, fake

- README.md
- Testing/What is robolectric.md
> Robolectric

- Kotlin/What's infix function.md
- README.md
> infix function

- General/OOP principles.md
- README.md
> OOP principles

- Patterns/Singleton pattern.md
- README.md
> Singleton pattern

- Kotlin/What's Ranges.md
- README.md
> Kotlin ranges

- Android/Difference between Room and SQLite.md
- README.md
> Room vs SQLite

- Java/Difference between Semaphore and Monitor.md
- README.md
> Semaphore vs monitor

- General/Composition vs Inheritance.md
- README.md
> Composition vs inheritance

- README.md
- Testing/What is functional testing.md
> functional testing

- README.md
- Testing/Unit testing vs Functional testing.md
> Functional test vs Unit test

- Patterns/Builder pattern.md
- README.md
> Builder pattern

- Java/What's Executor interface.md
- README.md
> Executor interface

- Kotlin/What is destructuring declarations.md
- README.md
> Destructuring declarations

- Patterns/Facade pattern.md
- README.md
> Facade pattern

- Patterns/Abstract factory pattern.md
- README.md
> Abstract factory

- Patterns/Adapter pattern.md
- README.md
> Adapter pattern

- General/What is the difference between abstraction and encapsulation.md
- README.md
> Abstraction vs encapsulation

- Patterns/Decorator pattern.md
- README.md
> Decorator pattern

- Patterns/Command pattern.md
- README.md
> Command pattern

- Kotlin/What you know about Any, Nothing, Unit types.md
- README.md
> Any, nothing, unit types

- Patterns/Iterator pattern.md
- README.md
> Iterator pattern

- Android/What's Widget.md
- README.md
> What is widget

- Patterns/State pattern.md
- README.md
> State pattern

- Patterns/Prototype pattern.md
- README.md
> Prototype pattern

- Java/What you know about TreeSet.md
- README.md
> TreeSet in java

- Kotlin/Null safety.md
- README.md
> Null safety in Kotlin

- Android/What's BroadcastReceiver.md
- README.md
> BroadcastReceiver

- Java/HashSet vs TreeSet.md
- README.md
> HashSet vs TreeSet

- Android/What security best practices you know.md
- README.md
> Security practices

- Android/What's Navigation component.md
- README.md
> Navigation component

- Android/What's data binding.md
- README.md
> Data binding

- Android/What you know about Parcelable.md
- README.md
> Parcelable

- Java/Difference between final, finally and finalize.md
- Java/Final modifier.md
> Final, finally, finalize

- Patterns/Visitor pattern.md
- README.md
> Visitor pattern

- General/What is the difference between git pull and git fetch.md
- README.md
> Git pull vs git fetch

- Android/Main components of Android application.md
- README.md
> Main components of android application

- Patterns/Memento pattern.md
- README.md
> Memento pattern

- Libraries/Which libraries for dependency injection you know.md
- README.md
> DI libraries

- Patterns/Template method pattern.md
- README.md
> template method pattern

- Kotlin/What you know about StateFlow.md
- README.md
> What is StateFlow

- Android/What's dark theme.md
- README.md
> Dark theme

- Java/What you know about Comparator interface.md
- README.md
> Comparator interface

- Android/What's RecyclerView.md
- README.md
> What is RecyclerView

- Patterns/Composite pattern.md
- README.md
> Composite pattern

- Android/What you know about DiffUtil.md
- README.md
> What you know about DiffUtil

- Patterns/Strategy pattern.md
- README.md
> Strategy pattern

- Java/What you know about Vector.md
- README.md
> Vector Java

- Java/What you know about Stack.md
- README.md
> Stack in Java

- Java/What you know about LinkedHashSet.md
- README.md
> LinkedHashSet

- Java/What you know about EnumSet.md
- README.md
> EnumSet Java

- Android/What you know about ArrayMap.md
- Android/What you know about SparseArray.md
- README.md
> SparseArray

- Android/What you know about Chrome custom tabs.md
- README.md
> Chrome Custom Tabs

- Patterns/Interpreter pattern.md
- README.md
> Interpreter pattern

- Java/What you know about EnumMap.md
- README.md
> EnumMap Java

- Kotlin/What is the difference between suspending vs. blocking.md
- README.md
> Issue #132 chore: Added difference between blocking and suspend in kotlin

- Patterns/Observer pattern.md
- README.md
> Observer pattern

- Java/What do you know about ConcurrentHashMap.md
- README.md
> ConcurrentHashMap

- General/SOAP vs REST.md
- README.md
> SOAP vs REST

- Java/What do you know about LinkedHashMap.md
- README.md
> LinkedHashMap

- Kotlin/What do you know about Channels.md
- README.md
> Kotlin Channels

- Java/Hashtable vs ConcurrentHashMap.md
- README.md
> Hashtable vs ConcurrentHashMap

- Patterns/Mediator pattern.md
- README.md
> Mediator pattern

- Kotlin/What do you know about StateFlow.md
> Improve StateFlow answer

- Libraries/What the difference between @Bind and @Provides in Dagger 2.md
- README.md
> Provides vs Binds

- Kotlin/What do you know about delegated properties.md
- README.md
> Delegated properties

- Patterns/Bridge pattern.md
- README.md
> Bridge pattern

- Android/What do you know about FileProvider.md
- README.md
> FileProvider

- Patterns/Flyweight pattern.md
- README.md
> Flyweight pattern

- Kotlin/What do you know about JvmOverloads annotation.md
- README.md
> JvmOverloads annotation

- Android/What do you know about Converters in Room.md
- README.md
> Converters in Room

- Patterns/Chain of Responsibility pattern.md
- README.md
> Chain of Responsibility pattern

- Java/What do you know about java record.md
- README.md
> Java record

- Java/What do you know about default method in interface.md
- README.md
> Default method in interface

- Android/What do you know about App Startup.md
- Android/What's Jetpack.md
- README.md
> App Startup

- Kotlin/Describe constructors invocation order.md
- README.md
> Kotlin constructors invocation order

- Java/Do objects get passed by reference or value.md
- README.md
> Do objects get passed by reference or value

- Android/What's Room.md
> Improve What's Room answer

- Kotlin/What is the difference between * and Any in generics.md
- README.md
> Difference between * and Any in Kotlin generics

- Kotlin/code/Questions.md
Added first few code questions/answers for Kotlin
> Code questions Kotlin

- README.md
- Rx/What is the difference between cold and hot observables.md
> Hot vs Cold Observables

- Android/What do you know about RecyclerView ItemDecoration.md
- README.md
> RecyclerView ItemDecoration

- General/What do you know about DI.md
- README.md
> What id Dependecy Injection

- Kotlin/What do you know about JvmStatic and JvmField annotations.md
- README.md
> JvmStatic & JvmField

- Kotlin/What do you know about StateFlow and SharedFlow.md
Improved answer about `StateFlow` and `SharedFlow`
> Improved StateFlow answer

- Rx/code/subscribeOn.md
> SubscribeOn puzzles

- Android/What do you know about Activity Result APIs.md
- README.md
> Issue-559: Activity Result APIs

- Android/What do you know about View Binding.md
- Android/What's data binding.md
> Improved View binding and Data binding answers

- General/What do you know about URL.md
- README.md
> What do you know about URL?

- General/What do you know about URI.md
- General/What is the difference between HTTP and HTTPS.md
> Improved URI/Http vs Https answers

- Libraries/What do you know about Realm.md
- README.md
> Realm overview

- Libraries/Main annotations in Dagger 2.md
- README.md
> Main annotations in Dagger 2

- Kotlin/What do you know about extensions?.md
- README.md
> Kotlin Extensions

- Kotlin/Inline keyword.md
> Improve inline keyword answer

- Kotlin/What do you know about Coroutine Job.md
- README.md
> Coroutine Job

- Libraries/What do you know about Koin.md
- README.md
> What do you know about Koin library

- Libraries/Which libraries for dependency injection you know.md
> Dependency injection libraries answer updated

- Android/What do you know about PendingIntent.md
> Improved PendingIntents answer

- Libraries/What do you know about Kodein.md
- README.md
> Kodein library

- Android/What do you know about App Bundles.md
- README.md
> What do you know about App Bundles?

- Android/What do you know about Play Feature Delivery.md
- README.md
> What do you know about Play Feature Delivery

- Java/What do you know about wildcard.md
- README.md
> Java Wildcard

- Kotlin/Generics.md
- README.md
> Kotlin generics

- Libraries/What do you know about OkHttp.md
- README.md
> What do you know about OkHttp?

- Android/Describe jetpack compose phases.md
> Further reading section in Compose phases answer

- Android/What do you know about App Bundles.md
> Updated What do you know about App Bundles answer

- Kotlin/What's difference between launch and async.md
- README.md
> What is the difference between `async` and `launch`?

- Java/Generics.md
> Added "Next Questions" section to "What do you know about Generics?" answer

- README.md
> Interview examples section in `README.md`

- Java/What's interface.md
- README.md
> Interface in Java

- Java/What is enum.md
> What is enum answer improved

- Java/Generics.md
> Added new links to `What do you know about generics` answer

- Libraries/What do you know about Retrofit.md
- README.md
> What do you know about Retrofit?

- Android/What is gradle.md
- README.md
> What is Gradle?

- Android/What do you know about ViewCompositionStrategy.md
- README.md
> `ViewCompositionStrategy`

- Android/What do you know about Version catalog.md
- README.md
> Version catalog

- Android/What is Fragment.md
> Added new links to "What is Fragment" asnwer

- Java/Describe Queue interface from java collection.md
> Add "Next questions" section to "Describe `Queue` interface" answer

- Android/What do you know about Auto Backup.md
- README.md
> What do you know about Auto Backup? answer

- Java/What do you know about Stream interface.md
- README.md
> `Stream` interface in Java

- Java/What do you know about double check pattern singleton.md
- README.md
> Double check singleton pattern

- Android/What tools for multithreading do you know.md
- README.md
> Tools for multithreading in Android

- General/What is Scrum.md
- README.md
> What is Scrum?

- Android/Describe android modularization in general.md
> Issue-695: Added "Next questions" section to "Describe android modularization in general" answer

- Java/What is volatile keyword.md
> "Next questions" section is added in "What is volatile keyword" answer

- Android/What do you know about accessibility.md
- README.md
> What do you know about accessibility?

- Android/What do you know about side effects in jetpack compose.md
> Improved "What do you know about side effects in jetpack compose?" answer

- Android/What do you know about taskAffinity.md
- README.md
> What do you know about `taskAffinity`

- Java/Describe List interface.md
> "Describe `List` interface" answer improved

- Android/What launch modes do you know.md
> "Next questions" section is added in "What launch modes do you know?" answer

- Kotlin/What do you know about type aliases.md
- README.md
> What do you know about type aliases?

- Android/What is ANR.md
> Added new link to "Further reading" section in "What is ANR" answer

- README.md
> Interview examples - Middle android developer (Rx stack)

- General/SOLID principles.md
> "Further reading" section added to "SOLID principles" answer

- General/What do you know about certificate pinning.md
- README.md
> What do you know about certificate pinning?

- Android/What ways do you know to reduce the size of an application.md
- README.md
> What ways do you know to reduce the size of an application?

- Android/What do you know about Intent Filter.md
- README.md
> What do you know about Intent Filter?

- Android/What do you know about downloadable fonts.md
> Added new link to "What do you know about downloadable fonts" answer

- Kotlin/What do you know about operator overloading.md
- README.md
> What do you know about operator overloading?

- Android/What do you know about Splash screen and SplashScreen library.md
- README.md
> What do you know about Splash screen and SplashScreen library?

- Kotlin/What do you know about StateFlow and SharedFlow.md
> Added new link to "What do you know about StateFlow and SharedFlow?" answer

- Android/What do you know about Foreground Services.md
- README.md
> What do you know about Foreground Services?

- Android/What do you know about Activity Result APIs.md
- Android/What do you know about Converters in Room.md
- Android/What is the difference between view binding and data binding.md
- Android/What you know about DataStore.md
- General/What do you know about DI.md
- Java/Describe set interface from java collection.md
- Java/What do you know about java record.md
- Kotlin/Describe constructors invocation order.md
- Kotlin/Describe nullability and null safety.md
- Kotlin/Inline keyword.md
- Kotlin/What do you know about Flow.md
- Kotlin/What do you know about JvmOverloads annotation.md
- Kotlin/What do you know about extensions?.md
- Kotlin/What is Coroutine Scope and how is that different from Coroutine Context?.md
- Libraries/What do you know about Realm.md
- Libraries/What do you know about hilt.md
- Patterns/MVI pattern.md
- Patterns/MVP pattern.md
- Patterns/MVVM pattern.md
- Testing/What is A_B testing.md
> Typos corrected

- General/What is Kanban.md
- README.md
> What is Kanban

- README.md
> Changed links for questions in `README.md`

- General/What is the difference between symmetric and asymmetric encryption.md
- README.md
> What is the difference between symmetric and asymmetric encryption?

- README.md
> Total number of questions counter added

- Kotlin/What do you know about data objects.md
- README.md
> What do you know about data objects?

- Kotlin/What do you know about property references.md
- README.md
> What do you know about property references and `::` operator?

- Android/What is StrictMode.md
- README.md
> What is `StrictMode`?

- README.md
> Added Discussions section to the `README.md`

- Android/What do you know about CompositionLocal.md
- README.md
> What do you know about `CompositionLocal`?

- Android/What is the difference between Activity and Fragment.md
- README.md
> What is the difference between `Activity` and `Fragment`?

- Kotlin/What is the difference between functional interfaces and type aliases.md
- README.md
> What is the difference between functional interfaces and type aliases?

- Patterns/Builder pattern.md
> Builder pattern (reworked)

- Patterns/Bridge pattern.md
> Bridge pattern (reworked)

- Patterns/Mediator pattern.md
> Mediator pattern (reworked)

- Patterns/Decorator pattern.md
> Decorator pattern (reworked)

- Patterns/Abstract factory pattern.md
> Abstract factory pattern (reworked).md

- Patterns/Prototype pattern.md
> Prototype pattern (reworked)

- Patterns/Composite pattern.md
> Composite pattern (reworked)

- Patterns/Memento pattern.md
> Memento pattern (reworked)

- Patterns/Chain of Responsibility pattern.md
> Chain of Responsibility pattern (reworked)
